name: BuildAndValidateTabularModel
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validation:
    runs-on: windows-latest
    environment: Dev
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Tabular Editor 2.x
        shell: pwsh
        run: .\Scripts\DownloadTE2.ps1

      - name: Deploy to Power BI
        shell: cmd
        run: TabularEditor.exe .\TestDataset -D "%AS_CONNECTIONSTRING%"
